#!/usr/bin/env bash
# Provision an Azure AI Foundry resource + gpt-4.1 deployment, then write .env.
#
# Prerequisite (interactive, do this first):
#     az login --use-device-code
#
# Usage:
#     ./scripts/provision_azure.sh [resource-name]
#
# Idempotent: an existing resource/deployment with the same name is reused.
# See docs/AZURE_SETUP.md for what each step does and why.
set -euo pipefail

SOLUTION_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPLOYMENT_NAME="${DEPLOYMENT_NAME:-gpt-4.1}"
MODEL_NAME="${MODEL_NAME:-gpt-4.1}"
CAPACITY="${CAPACITY:-10}"
CANDIDATE_REGIONS=(${REGIONS:-eastus2 swedencentral westus3 eastus northcentralus})

step() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
die()  { printf '\033[31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

step "Verifying sign-in"
az account show -o none 2>/dev/null || die "Not signed in. Run: az login --use-device-code"
az account show --query "{subscription:name, user:user.name}" -o table

step "Locating a resource group"
RG="${RESOURCE_GROUP:-$(az group list --query "[0].name" -o tsv)}"
if [[ -z "$RG" || "$RG" == "null" ]]; then
  RG="rg-agentic-analysis"
  echo "No resource group found; creating $RG"
  az group create --name "$RG" --location "${CANDIDATE_REGIONS[0]}" -o none \
    || die "Could not create a resource group. Lab subscriptions often deny this; set RESOURCE_GROUP=<existing>."
fi
echo "Using resource group: $RG"

step "Finding a region that offers $MODEL_NAME with quota"
REGION=""; MODEL_VERSION=""; SKU=""
for CANDIDATE in "${CANDIDATE_REGIONS[@]}"; do
  ROW=$(az cognitiveservices model list --location "$CANDIDATE" \
        --query "[?model.name=='${MODEL_NAME}'] | [0].{v:model.version, s:model.skus[?name=='GlobalStandard']|[0].name}" \
        -o tsv 2>/dev/null || true)
  [[ -z "$ROW" ]] && { echo "  $CANDIDATE: model not offered"; continue; }
  MODEL_VERSION=$(echo "$ROW" | cut -f1)
  SKU=$(echo "$ROW" | cut -f2)
  [[ -z "$SKU" || "$SKU" == "None" ]] && SKU="Standard"
  echo "  $CANDIDATE: version=$MODEL_VERSION sku=$SKU"
  REGION="$CANDIDATE"
  break
done
[[ -z "$REGION" ]] && die "$MODEL_NAME is not available in any candidate region. Try REGIONS='...' with more regions."

echo "Quota in $REGION:"
az cognitiveservices usage list --location "$REGION" \
  --query "[?contains(name.value, 'GPT-4.1') || contains(name.value,'OpenAI.GlobalStandard')].{quota:name.localizedValue, used:currentValue, limit:limit}" \
  -o table 2>/dev/null || echo "  (usage query unavailable)"

step "Creating the Azure AI Foundry resource"
NAME="${1:-${RESOURCE_NAME:-aifoundry-agentic-$(date +%s | tail -c 6)}}"
if az cognitiveservices account show --name "$NAME" -g "$RG" -o none 2>/dev/null; then
  echo "Resource $NAME already exists; reusing it."
else
  az cognitiveservices account create \
    --name "$NAME" --resource-group "$RG" --location "$REGION" \
    --kind AIServices --sku S0 --custom-domain "$NAME" --yes -o none
  echo "Created $NAME in $REGION"
fi

step "Deploying $MODEL_NAME as '$DEPLOYMENT_NAME'"
if az cognitiveservices account deployment show --name "$NAME" -g "$RG" \
     --deployment-name "$DEPLOYMENT_NAME" -o none 2>/dev/null; then
  echo "Deployment $DEPLOYMENT_NAME already exists; reusing it."
else
  az cognitiveservices account deployment create \
    --name "$NAME" --resource-group "$RG" \
    --deployment-name "$DEPLOYMENT_NAME" \
    --model-name "$MODEL_NAME" --model-version "$MODEL_VERSION" --model-format OpenAI \
    --sku-name "$SKU" --sku-capacity "$CAPACITY" -o none
fi
az cognitiveservices account deployment show --name "$NAME" -g "$RG" \
  --deployment-name "$DEPLOYMENT_NAME" \
  --query "{state:properties.provisioningState, model:properties.model.name, version:properties.model.version, capacity:sku.capacity}" -o table

step "Writing $SOLUTION_DIR/.env"
KEY=$(az cognitiveservices account keys list --name "$NAME" -g "$RG" --query key1 -o tsv)
ENDPOINT=$(az cognitiveservices account show --name "$NAME" -g "$RG" --query properties.endpoint -o tsv)
umask 077
cat > "$SOLUTION_DIR/.env" <<EOF
# Generated by scripts/provision_azure.sh
# Resource: $NAME   Resource group: $RG   Region: $REGION
AZURE_OPENAI_KEY=$KEY
URL=$ENDPOINT
AZURE_OPENAI_DEPLOYMENT=$DEPLOYMENT_NAME
EOF
echo "Endpoint: $ENDPOINT"

step "Verifying the deployment answers"
CODE=$(curl -sS -o /dev/null -w "%{http_code}" \
  "${ENDPOINT%/}/openai/deployments/${DEPLOYMENT_NAME}/chat/completions?api-version=2024-05-01-preview" \
  -H "Content-Type: application/json" -H "api-key: $KEY" \
  -d '{"messages":[{"role":"user","content":"ping"}],"max_tokens":5}')
[[ "$CODE" == "200" ]] || die "Endpoint returned HTTP $CODE. See the troubleshooting table in docs/AZURE_SETUP.md."
echo "HTTP 200 - credentials verified."

step "Done"
cat <<EOF
Resource group : $RG
Resource       : $NAME ($REGION)
Deployment     : $DEPLOYMENT_NAME ($MODEL_NAME $MODEL_VERSION, $SKU, ${CAPACITY}K TPM)
Credentials    : $SOLUTION_DIR/.env

Next:  cd $SOLUTION_DIR && python final.py --csv data/data-Marketing-1.csv

Teardown later:
  az cognitiveservices account delete --name $NAME -g $RG
  az cognitiveservices account purge  --name $NAME -g $RG -l $REGION
EOF
